### ISSUE TITLE
few problems

### ISSUE THREAD

**Issue by NeonLightning** [joel16/VITA-Homebrew-Sorter#1]
when i tried to sort let's just say it didn't work
first off it didn't sort them
second it placed icons that randomly changed between icons in the middle of the screen
if you try to access the options on those to move them the vita freezes.
like the idea of this app. but it doesn't seem to work. also once it gets a bit more stable it'd be nice to be able to put things in folders via this app.

**Comment by joel16** [comment]
Ok just to debug this, is there any logs left behind? Can you check ux0:data/VITAHomebrewSorter/debug.log to see if there's anything?
Also how many vita applications do you currently have? Just so you know you can restore your backup before you sort again. I'll make sure this doesn't overwrite by saving timestamps instead for next release.

**Comment by NeonLightning** [comment]
i did restore successfully and i'm not sure i think around 83 things on the livearea right now. debug.log is blank

**Comment by joel16** [comment]
That is indeed weird, I can't debug this blindly so I'll try to get some testers from discord to see this through. Also, I made a new release which isn't targeting to fix this but rather it makes an initial backup that doesn't get overwritten each time the "apply sort" is used. This is just a fallback measure incase anything goes wrong. (For example user clicking sort twice would've already lost their initial backup as it would be overwritten.)

**Comment by joel16** [comment]
Hey, if it's not too much to ask could you upload a copy of your app.db so I can try to debug it and see what the problem is?

**Comment by NeonLightning** [comment]
[app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6321629/app.zip)

**Comment by NeonLightning** [comment]
it might be because i have asian characters in some of my games

**Comment by joel16** [comment]
> it might be because i have asian characters in some of my games

I was wondering the same. I will mess around with this and get back to you.

**Comment by joel16** [comment]
Alright looks like it was due to an issue with folders. I had to track other fields that I wasn't tracking before since multiple folders with the same names can exist and it kept hitting a SQL unique constraint. Here's a test VPK than ran fine on my device and sorted your db as well mine. Please make a manual backup of your db too, just to be safe. If you can confirm this is working, I'll push another release. 

[Vita Homebrew Sort v1.10 TEST.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6327416/Vita.Homebrew.Sort.v1.10.TEST.zip)

**Comment by NeonLightning** [comment]
works now :)

**Comment by joel16** [comment]
Thank you for approving. I'll also take a look into your suggestion at a later time.
