### ISSUE TITLE
PSTV compatibility

### ISSUE THREAD

**Issue by agiat86** [joel16/VITA-Homebrew-Sorter#8]
Can't do anything on my PSTV. I think it can't handle the Power bubble.

**Comment by joel16** [comment]
This doesn't really help much. Does the app even boot? Is the sort failing? 
If any of those are true I'll need a copy of your app.db.

**Comment by agiat86** [comment]
The sort is failing. Here you go, I'm attaching my app.db. (Github insisted I must compress it, though)
[app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/7775223/app.zip)

**Comment by joel16** [comment]
I will take a look when I get some time, thanks.

**Comment by joel16** [comment]
~~Can you do me a favour, could you restart your device and try again? If that doesn't work can you resend the app.db. Cause there's an icon/folder that makes no sense.~~ Nevermind I see what the issue is.

**Comment by joel16** [comment]
Could you try this and let me know if it sorts?

[VITA-Homebrew-Sorter.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/7791769/VITA-Homebrew-Sorter.zip)

**Comment by agiat86** [comment]
Yes, it works now! Thanks. Although I noticed that the Power bubble is the very first now. It's okay, though. I think I prefer it this way anyway.

**Comment by joel16** [comment]
Unfortunately yeah, it doesn't get into the sorting algorithm since it has no title or titleID so it just checked for that at the start and puts it there. Thanks for confirming. I'll update the release builds.
